[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "revm primitives"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm", "types"]
license = "MIT"
name = "revm-primitives"
repository = "https://github.com/bluealloy/revm"
version = "3.1.1"
readme = "../../README.md"

# Don't need to run build script outside of this repo
exclude = ["build.rs", "src/kzg/*.txt"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
alloy-primitives = { version = "0.7", default-features = false, features = [
    "rlp",
] }
hashbrown = "0.14"
auto_impl = "1.2"
bitvec = { version = "1", default-features = false, features = ["alloc"] }
bitflags = { version = "2.5.0", default-features = false }

# For setting the CfgEnv KZGSettings. Enabled by c-kzg flag.
c-kzg = { version = "1.0.0", default-features = false, optional = true }
once_cell = { version = "1.19", default-features = false, optional = true }

# utility
enumn = "0.1"
derive_more = { version = "0.99", optional = true }
cfg-if = "1"
dyn-clone = "1.0"

# optional
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "rc",
], optional = true }

[build-dependencies]
hex = { version = "0.4", default-features = false }

[features]
default = ["std", "c-kzg", "portable"]
std = [
    "serde?/std",
    "alloy-primitives/std",
    "hex/std",
    "bitvec/std",
    "bitflags/std",
]
serde = [
    "dep:serde",
    "alloy-primitives/serde",
    "hex/serde",
    "hashbrown/serde",
    "bitvec/serde",
    "bitflags/serde",
    "c-kzg?/serde",
]
arbitrary = ["std", "alloy-primitives/arbitrary", "bitflags/arbitrary"]
asm-keccak = ["alloy-primitives/asm-keccak"]
portable = ["c-kzg?/portable"]

optimism = []
# Optimism default handler enabled Optimism handler register by default in EvmBuilder.
optimism-default-handler = ["optimism"]
negate-optimism-default-handler = []

dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
    "optional_beneficiary_reward",
]
memory_limit = []
optional_balance_check = []
optional_block_gas_limit = []
optional_eip3607 = []
optional_gas_refund = []
optional_no_base_fee = []
optional_beneficiary_reward = []

# See comments in `revm-precompile`
c-kzg = ["dep:c-kzg", "dep:once_cell", "dep:derive_more"]

opbnb = []
opbnb-default-handler = ["opbnb"]
negate-opbnb-default-handler = []