[package]
authors = ["Dragan Rakita <dragan0rakita@gmail.com>"]
description = "revm Interpreter"
edition = "2021"
keywords = ["no_std", "ethereum", "evm", "revm", "interpreter"]
license = "MIT"
name = "revm-interpreter"
repository = "https://github.com/bluealloy/revm"
version = "5.0.0"
readme = "../../README.md"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lints.rust]
unreachable_pub = "warn"
unused_must_use = "deny"
rust_2018_idioms = "deny"

[lints.rustdoc]
all = "warn"

[dependencies]
revm-primitives = { path = "../primitives", version = "4.0.0", default-features = false }

paste = { version = "1.0", optional = true }
phf = { version = "0.11", default-features = false, optional = true, features = [
    "macros",
] }

# optional
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "rc",
], optional = true }

[dev-dependencies]
walkdir = "2.5"
serde_json = "1.0"
bincode = "1.3"

[[test]]
name = "eof"
path = "tests/eof.rs"
required-features = ["serde"]

[features]
default = ["std", "parse"]
std = ["serde?/std", "revm-primitives/std"]
hashbrown = ["revm-primitives/hashbrown"]
serde = ["dep:serde", "revm-primitives/serde"]
arbitrary = ["std", "revm-primitives/arbitrary"]
asm-keccak = ["revm-primitives/asm-keccak"]
portable = ["revm-primitives/portable"]
parse = ["dep:paste", "dep:phf"]

bsc = ["revm-primitives/bsc"]
optimism = ["revm-primitives/optimism"]
# Optimism default handler enabled Optimism handler register by default in EvmBuilder.
optimism-default-handler = [
    "optimism",
    "revm-primitives/optimism-default-handler",
]
negate-optimism-default-handler = [
    "revm-primitives/negate-optimism-default-handler",
]

dev = [
    "memory_limit",
    "optional_balance_check",
    "optional_block_gas_limit",
    "optional_eip3607",
    "optional_gas_refund",
    "optional_no_base_fee",
    "optional_beneficiary_reward",
]
memory_limit = ["revm-primitives/memory_limit"]
optional_balance_check = ["revm-primitives/optional_balance_check"]
optional_block_gas_limit = ["revm-primitives/optional_block_gas_limit"]
optional_eip3607 = ["revm-primitives/optional_eip3607"]
optional_gas_refund = ["revm-primitives/optional_gas_refund"]
optional_no_base_fee = ["revm-primitives/optional_no_base_fee"]
optional_beneficiary_reward = ["revm-primitives/optional_beneficiary_reward"]
opbnb = ["revm-primitives/opbnb"]
opbnb-default-handler = [
    "opbnb",
    "revm-primitives/opbnb-default-handler",
]
negate-opbnb-default-handler = [
    "revm-primitives/negate-opbnb-default-handler",
]